# Generated by Django 5.0.4 on 2024-05-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
