# Generated by Django 5.0.4 on 2024-05-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cont_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont',
            name='Contact',
            field=models.IntegerField(max_length=20),
        ),
    ]
